// Starter menu seeded on first boot (see MenuService.onModuleInit) until the
// admin menu editor exists. Copy is written the way a Greek menu would be.
export const SAMPLE_MENU_ITEMS = [
  {
    id: "seed-bowl-kotopoulo-kinoa",
    imageUrl: "https://images.unsplash.com/photo-1520066391310-428f06ebd602?auto=format&fit=crop&w=900&q=70",
    allergens: ["milk"],
    name: "Bowl κοτόπουλο & κινόα",
    description: "Ψητό κοτόπουλο, κινόα, αβοκάντο, ντοματίνια, σάλτσα γιαουρτιού",
    priceCents: 850,
    portionWeightG: 420,
    calories: 540,
    proteinG: 42,
    carbsG: 48,
    fatG: 18,
  },
  {
    id: "seed-solomos-glykopatata",
    imageUrl: "https://images.unsplash.com/photo-1601316585772-ba1e6dae9cfc?auto=format&fit=crop&w=900&q=70",
    allergens: ["fish"],
    name: "Σολομός με γλυκοπατάτα",
    description: "Ψητός σολομός, πουρές γλυκοπατάτας, μπρόκολο στον ατμό",
    priceCents: 980,
    portionWeightG: 400,
    calories: 610,
    proteinG: 38,
    carbsG: 42,
    fatG: 28,
  },
  {
    id: "seed-vegan-fakes",
    imageUrl: "https://images.unsplash.com/photo-1763000215238-38350d3e41ac?auto=format&fit=crop&w=900&q=70",
    dietTags: ["vegan", "vegetarian"],
    allergens: ["sesame"],
    name: "Vegan bowl με φακές",
    description: "Φακές, καστανό ρύζι, λαχανικά εποχής, ταχίνι",
    priceCents: 750,
    portionWeightG: 400,
    calories: 480,
    proteinG: 22,
    carbsG: 68,
    fatG: 14,
  },
  {
    id: "seed-salad-elliniki-kotopoulo",
    imageUrl: "https://images.unsplash.com/photo-1631311695255-8dde6bf96cb5?auto=format&fit=crop&w=900&q=70",
    allergens: ["milk"],
    name: "Ελληνική σαλάτα με κοτόπουλο",
    description: "Ντομάτα, αγγούρι, φέτα, ελιές Καλαμών, ψητό κοτόπουλο, παρθένο ελαιόλαδο",
    priceCents: 800,
    portionWeightG: 380,
    calories: 460,
    proteinG: 34,
    carbsG: 18,
    fatG: 28,
  },
  {
    id: "seed-wrap-galopoula",
    imageUrl: "https://images.unsplash.com/photo-1646530208887-8a791bff4701?auto=format&fit=crop&w=900&q=70",
    allergens: ["gluten"],
    name: "Wrap γαλοπούλας με λαχανικά",
    description: "Τορτίγια ολικής άλεσης, γαλοπούλα, λαχανικά, αβοκάντο",
    priceCents: 700,
    portionWeightG: 320,
    calories: 420,
    proteinG: 30,
    carbsG: 40,
    fatG: 14,
  },
  {
    id: "seed-buddha-bowl",
    imageUrl: "https://images.unsplash.com/photo-1623428188474-b1d532c5e560?auto=format&fit=crop&w=900&q=70",
    dietTags: ["vegan", "vegetarian"],
    allergens: ["sesame"],
    name: "Buddha bowl λαχανικών",
    description: "Ψητά λαχανικά εποχής, χούμους, κινόα, σπόροι",
    priceCents: 780,
    portionWeightG: 400,
    calories: 500,
    proteinG: 18,
    carbsG: 60,
    fatG: 20,
  },
];
