export const SAMPLE_MENU_ITEMS = [
  {
    id: "seed-bowl-kotopoulo-kinoa",
    name: "Bowl κοτόπουλο & κινόα",
    description: "Ψητό κοτόπουλο, κινόα, avocado, cherry ντομάτες, sauce γιαουρτιού",
    priceCents: 850,
    portionWeightG: 420,
    calories: 540,
    proteinG: 42,
    carbsG: 48,
    fatG: 18,
  },
  {
    id: "seed-solomos-glykopatata",
    name: "Σολομός με γλυκοπατάτα",
    description: "Ψητός σολομός, πουρές γλυκοπατάτας, μπρόκολο ατμού",
    priceCents: 980,
    portionWeightG: 400,
    calories: 610,
    proteinG: 38,
    carbsG: 42,
    fatG: 28,
  },
  {
    id: "seed-vegan-fakes",
    name: "Vegan bowl με φακές",
    description: "Φακές, καστανό ρύζι, λαχανικά, ταχίνι",
    priceCents: 750,
    portionWeightG: 400,
    calories: 480,
    proteinG: 22,
    carbsG: 68,
    fatG: 14,
  },
  {
    id: "seed-salad-elliniki-kotopoulo",
    name: "Salad ελληνική με κοτόπουλο",
    description: "Ντομάτα, αγγούρι, φέτα, ελιές, ψητό κοτόπουλο, ελαιόλαδο",
    priceCents: 800,
    portionWeightG: 380,
    calories: 460,
    proteinG: 34,
    carbsG: 18,
    fatG: 28,
  },
  {
    id: "seed-wrap-galopoula",
    name: "Wrap γαλοπούλα & λαχανικά",
    description: "Ολικής άλεσης wrap, γαλοπούλα, λαχανικά, avocado",
    priceCents: 700,
    portionWeightG: 320,
    calories: 420,
    proteinG: 30,
    carbsG: 40,
    fatG: 14,
  },
  {
    id: "seed-buddha-bowl",
    name: "Buddha bowl λαχανικών",
    description: "Εποχιακά ψητά λαχανικά, χούμους, κινόα, σπόροι",
    priceCents: 780,
    portionWeightG: 400,
    calories: 500,
    proteinG: 18,
    carbsG: 60,
    fatG: 20,
  },
];
